# Generated by Django 5.0.7 on 2024-10-30 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vaccination', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=20)),
                ('child_age', models.CharField(max_length=100)),
                ('child_address', models.TextField()),
                ('child_dob', models.DateField()),
                ('child_father_name', models.CharField(max_length=20)),
                ('child_mother_name', models.CharField(max_length=20)),
                ('child_ph', models.BigIntegerField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccination.userdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Book_Appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appoinment_date', models.DateField()),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.vaccinations')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent.child_details')),
            ],
        ),
        migrations.CreateModel(
            name='appoinment_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appoinment_date', models.DateField()),
                ('appoinment_status', models.CharField(default='pending', max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.vaccinations')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent.child_details')),
            ],
        ),
        migrations.CreateModel(
            name='Child_vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_date', models.CharField(max_length=100, null=True)),
                ('vaccine_date', models.DateField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent.child_details')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.vaccinations')),
            ],
        ),
    ]
